# Generated by Django 4.2.7 on 2023-12-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='decription',
            new_name='description',
        ),
    ]
